@startuml
'https://plantuml.com/state-diagram

hide empty description

state base
state clicked
state dragging
state released
state aiming


[*] --> base

base --> clicked : LMB

clicked --> dragging : mouse motion

dragging --> released : LMB pressed or released

dragging --> base : RMB cancel

released --> base : is outside DropArea

released --> [*] : inside DropArea

dragging --> aiming
note on link
single target card
|| on drop area
end note

aiming --> released : card play confirmed

aiming --> base
note on link
RMB || mouse too low
end note

@enduml